# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pb/men/men.proto

require 'google/protobuf'


descriptor_data = "\n\x10pb/men/men.proto\x12\x03men\"\x1e\n\rGetMenRequest\x12\r\n\x05tenpo\x18\x01 \x01(\t\"\'\n\x0eGetMenResponse\x12\x15\n\x03men\x18\x01 \x01(\x0b\x32\x08.men.Men\"%\n\x03Men\x12\x0e\n\x06\x66utosa\x18\x01 \x01(\t\x12\x0e\n\x06katasa\x18\x02 \x01(\t2A\n\nMenService\x12\x33\n\x06GetMen\x12\x12.men.GetMenRequest\x1a\x13.men.GetMenResponse\"\x00\x42\x07Z\x05./menb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Men
  GetMenRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("men.GetMenRequest").msgclass
  GetMenResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("men.GetMenResponse").msgclass
  Men = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("men.Men").msgclass
end
