# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: pb/men/men.proto for package 'men'

require 'grpc'
require './men_pb'

module Men
  module MenService
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'men.MenService'

      rpc :GetMen, ::Men::GetMenRequest, ::Men::GetMenResponse
    end

    Stub = Service.rpc_stub_class
  end
end
