# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import buta_pb as buta__pb


class ButaServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetButa = channel.unary_unary(
                '/buta.ButaService/GetButa',
                request_serializer=buta__pb.GetButaRequest.SerializeToString,
                response_deserializer=buta__pb.GetButaResponse.FromString,
                )


class ButaServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetButa(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ButaServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetButa': grpc.unary_unary_rpc_method_handler(
                    servicer.GetButa,
                    request_deserializer=buta__pb.GetButaRequest.FromString,
                    response_serializer=buta__pb.GetButaResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'buta.ButaService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ButaService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetButa(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/buta.ButaService/GetButa',
            buta__pb.GetButaRequest.SerializeToString,
            buta__pb.GetButaResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
