# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: buta.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nbuta.proto\x12\x04\x62uta\"\x1f\n\x0eGetButaRequest\x12\r\n\x05tenpo\x18\x01 \x01(\t\"!\n\x0fGetButaResponse\x12\x0e\n\x06volume\x18\x01 \x01(\t2G\n\x0b\x42utaService\x12\x38\n\x07GetButa\x12\x14.buta.GetButaRequest\x1a\x15.buta.GetButaResponse\"\x00\x42\x08Z\x06./butab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'buta_pb', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\006./buta'
  _globals['_GETBUTAREQUEST']._serialized_start=20
  _globals['_GETBUTAREQUEST']._serialized_end=51
  _globals['_GETBUTARESPONSE']._serialized_start=53
  _globals['_GETBUTARESPONSE']._serialized_end=86
  _globals['_BUTASERVICE']._serialized_start=88
  _globals['_BUTASERVICE']._serialized_end=159
# @@protoc_insertion_point(module_scope)
